Update Ansible Molecule scenario
A long time has passed since we tested this role with Ansible Molecule.

We are on Debian/bookworm now and used an Python venv environment with
the following ansible / molecule version to recreate everything:

  ❯ molecule --version
  molecule 25.7.0 using python 3.11
      ansible:2.18.8
      azure:25.8.12 from molecule_plugins
      default:25.7.0 from molecule
      ec2:25.8.12 from molecule_plugins
      openstack:25.8.12 from molecule_plugins requiring collections: openstack.cloud>=2.1.0
      gce:25.8.12 from molecule_plugins requiring collections: google.cloud>=1.0.2 community.crypto>=1.8.0
      podman:25.8.12 from molecule_plugins requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
      docker:25.8.12 from molecule_plugins requiring collections: community.docker>=3.10.2 ansible.posix>=1.4.0
      containers:25.8.12 from molecule_plugins requiring collections: ansible.posix>=1.3.0 community.docker>=1.9.1 containers.podman>=1.8.1
      vagrant:25.8.12 from molecule_plugins

  ❯ molecule init scenario -s podman -d podman

  ❯ molecule init scenario -d docker

I made the default scenario with docker driver which will be used for
the Github Workflow.

To make converge.yml work with the role name 'jkirk.proxmox' the
namespace in meta.yml had to be updated.

The role now supports Debian/bookworm + Debian/trixie only, so updated
the platforms versions in meta.yml accordingy.

Docker molecule image was set to Debian images from geerlingguy.

In converge.yml we added the pre_tasks to print ansible_facts for
debugging, because I could not figure out why the "External IP must be
resolvable in /etc/hosts" in tasks/main.yml failed with the following
error:

  TASK [jkirk.proxmox : External IP must be resolvable in /etc/hosts] ************
  task path: /home/jkirk/projects/ansible/ansible-role-proxmox/tasks/main.yml:22
  redirecting (type: connection) ansible.builtin.podman to containers.podman.podman
  <instance> RUN [b'/usr/bin/podman', b'mount', b'instance']
  <instance> RUN [b'/usr/bin/podman', b'exec', b'instance', b'/bin/sh', b'-c', b'echo ~ && sleep 0']
  <instance> RUN [b'/usr/bin/podman', b'exec', b'instance', b'/bin/sh', b'-c', b'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1757003984.4501648-775013-49977526579587 `" && echo ansible-tmp-1757003984.4501648-775013-49977526579587="` echo /root/.ansible/tmp/ansible-tmp-1757003984.4501648-775013-49977526579587 `" ) && sleep 0']
  Using module file /home/jkirk/projects/ansible/ansible-role-proxmox/venv/lib/python3.11/site-packages/ansible/modules/lineinfile.py
  <instance> PUT /home/jkirk/.ansible/tmp/ansible-local-774358stphyhnr/tmp8kfy4qpb TO /root/.ansible/tmp/ansible-tmp-1757003984.4501648-775013-49977526579587/AnsiballZ_lineinfile.py
  <instance> RUN [b'/usr/bin/podman', b'cp', b'/home/jkirk/.ansible/tmp/ansible-local-774358stphyhnr/tmp8kfy4qpb', b'instance:/root/.ansible/tmp/ansible-tmp-1757003984.4501648-775013-49977526579587/AnsiballZ_lineinfile.py']
  <instance> RUN [b'/usr/bin/podman', b'exec', b'instance', b'/bin/sh', b'-c', b'chmod u+rwx /root/.ansible/tmp/ansible-tmp-1757003984.4501648-775013-49977526579587/ /root/.ansible/tmp/ansible-tmp-1757003984.4501648-775013-49977526579587/AnsiballZ_lineinfile.py && sleep 0']
  <instance> RUN [b'/usr/bin/podman', b'exec', b'instance', b'/bin/sh', b'-c', b"sudo -H -S -n  -u root /bin/sh -c 'echo BECOME-SUCCESS-mnjofwozefqsxwunqpoubcsztzjjwnrd ; /usr/bin/python3.11 /root/.ansible/tmp/ansible-tmp-1757003984.4501648-775013-49977526579587/AnsiballZ_lineinfile.py' && sleep 0"]
  <instance> RUN [b'/usr/bin/podman', b'exec', b'instance', b'/bin/sh', b'-c', b'rm -f -r /root/.ansible/tmp/ansible-tmp-1757003984.4501648-775013-49977526579587/ > /dev/null 2>&1 && sleep 0']
  The full traceback is:
  Traceback (most recent call last):
    File "/tmp/ansible_lineinfile_payload_1vvxap0b/ansible_lineinfile_payload.zip/ansible/module_utils/basic.py", line 1615, in atomic_move os.rename(b_src, b_dest)
  OSError: [Errno 16] Device or resource busy: b'/root/.ansible/tmp/ansible-tmp-1757003984.4501648-775013-49977526579587/tmpem1yqwxj' -> b'/etc/hosts'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/ansible_lineinfile_payload_1vvxap0b/ansible_lineinfile_payload.zip/ansible/module_utils/basic.py", line 1671, in atomic_move
      os.rename(b_tmp_dest_name, b_dest)
  OSError: [Errno 16] Device or resource busy: b'/etc/.ansible_tmpjhofho9mhosts' -> b'/etc/hosts'
  fatal: [instance]: FAILED! => {
      "changed": false,
      "invocation": {
          "module_args": {
              "attributes": null,
              "backrefs": false,
              "backup": false,
              "create": false,
              "dest": "/etc/hosts",
              "firstmatch": false,
              "group": null,
              "insertafter": null,
              "insertbefore": null,
              "line": "10.0.2.100 instance instance",
              "mode": null,
              "owner": null,
              "path": "/etc/hosts",
              "regexp": ".*instance",
              "search_string": null,
              "selevel": null,
              "serole": null,
              "setype": null,
              "seuser": null,
              "state": "present",
              "unsafe_writes": false,
              "validate": null
          }
      },
      "msg": "Unable to make /root/.ansible/tmp/ansible-tmp-1757003984.4501648-775013-49977526579587/tmpem1yqwxj into to /etc/hosts, failed final rename from b'/etc/.ansible_tmpjhofho9mhosts': [Errno 16] Device or resource busy: b'/etc/.ansible_tmpjhofho9mhosts' -> b'/etc/hosts'"
  }

It turned out that modifying /etc/hosts in a docker/podman container is
tricky, see: https://github.com/ansible/molecule/issues/2060

Decided to skip the task in question with the tag "molecule-notest",
see: https://ansible.readthedocs.io/projects/molecule/configuration/?h=tags#ansible